services:
  - type: web
    env: python
    autoDeploy: false
    envFile: .env
    startCommand: "gunicorn app:app"
    staticPublishPathPattern: "static/"
    healthCheckPath: /
    dockerfileCommands:
      - pip install --trusted-host pypi.python.org -r requirements.txt
      - python app.py  # or any other commands to build your app

databases: ~
